export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SAVE_SHIPPING_REQUEST = 'SAVE_SHIPPING_REQUEST';
export const SAVE_SHIPPING_SUCCESS = 'SAVE_SHIPPING_SUCCESS';
export const SAVE_SHIPPING_FAIL = 'SAVE_SHIPPING_FAIL';
export const SAVE_PAYMENT_REQUEST = 'SAVE_PAYMENT_REQUEST';
export const SAVE_PAYMENT_SUCCESS = 'SAVE_PAYMENT_SUCCESS';
export const SAVE_PAYMENT_FAIL = 'SAVE_PAYMENT_FAIL';
